### ISSUE TITLE
a basic question about TTA

### ISSUE THREAD

**Issue by Bojian-Chen** [mariodoebler/test-time-adaptation#12]
Hi, 
I have a basic question:
Is the main difference between test-time adaptation and sourece-free domain adaptation in the testing phase, where test-time domain adaptation is trested after only one training epoch?

**Comment by RobMarsden** [comment]
Hi,
in online settings, the predictions are evaluated directly as they are needed immediately. Offline settings do not have such requirements and can therefore adapt the model over several epochs. In online/offline test time adaptation, the model is adapted directly to the test data. In the default UDA setting, the model is adapted on the training dataset of the target domain (such as Cityscapes train) and then evaluated on another test dataset (Cityscapes eval). One could say that this is a two stage approach, while the idea of TTA is to employ the algorithm always at test-time. I hope this helps.
