### ISSUE TITLE
Unable to run ViT experiments

### ISSUE THREAD

**Issue by goirik-chakrabarty** [mariodoebler/test-time-adaptation#13]
Hi,

Firstly, thanks a lot for the excellent repo! I was trying to use the transformer architectures to reproduce the numbers however I am not able to understand which ARCH_NAME to use. The split_head function also gives an error. 

This may be due to a mismatch in the Timm version, but I am unsure.

**Comment by RobMarsden** [comment]
Hi,

all our experiments use the models provided by torchvision. If you want to reproduce some of the experiments, you should have a look at the [run.sh](https://github.com/mariodoebler/test-time-adaptation/blob/main/classification/scripts/run.sh). Alternatively, you can manually set `MODEL.ARCH` to `vit_b_16` or `swin_b`. If you encounter any errors after updating the environment, please provide the details.

**Comment by manogna-s** [comment]
Hi,

I had the same issue. I was able to use `vit_b_16` architecture. However, I get this error on using `swin_b` :

`    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'SwinTransformer' object has no attribute 'patch_embed'`

Any suggestions to resolve this?

**Comment by RobMarsden** [comment]
Hi,
can you provide the configuration you are using?

**Comment by goirik-chakrabarty** [comment]
Thank you! @RobMarsden it worked for me.
