### ISSUE TITLE
.pt download fail

### ISSUE THREAD

**Issue by Xiaoxx1111** [mariodoebler/test-time-adaptation#14]
hello,Hello, this is a very good job for me，but when I run the cifar_100C/tent.yaml file, I can't download the pt file, how to download it in the web version? In which folder will I put it after downloading?
Download started: path=ckpt/cifar100/corruptions/Hendrycks2020AugMix_ResNeXt.pt (gdrive_id=1ocnHbvDdOBLvgNr6K7vEYL08hUdkD1Rv)
////
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443)

**Comment by RobMarsden** [comment]
Hi,
Unfortunately I could not reproduce your error. In my case,  the download started automatically and everything worked as expected.
Best regards,
Rob
