### ISSUE TITLE
type error

### ISSUE THREAD

**Issue by Xiaoxx1111** [mariodoebler/test-time-adaptation#16]
File "/home/user5/code/test-time-adaptation-main/classification/robustbench/zenodo_download.py", line 83, in zenodo_download
    format=file["type"])
           ~~~~^^^^^^^^
KeyError: 'type'
May I ask what is the reason for this error?Looking forward to your reply, thank you！

**Comment by RobMarsden** [comment]
Can you provide more information about the setting you were trying to run?

**Comment by Xiaoxx1111** [comment]
I'm running forgetting.sh this script is set to the CIFAR10-C validation set, and this error occurs after the script automatically downloads the CIFAR10-C dataset

**Comment by RobMarsden** [comment]
I did not encounter any errors when setting `MODEL.ARCH Standard`. Please note that `forgetting.sh` is only intended for ImageNet-C, as the default models may not exist for other benchmarks.
