### ISSUE TITLE
Error while running MODEL.ARCH Vit-B-16/ Vit-L-14/Vit-B-32  on CLIP-like models

### ISSUE THREAD

**Issue by IFTEE-KUET-CSE** [mariodoebler/test-time-adaptation#17]
![git issue](https://github.com/mariodoebler/test-time-adaptation/assets/83751655/385b8a5b-a780-4a61-be6e-ef1ba23763fd)
It shows an error while running the command such as 
python test_time.py --cfg cfgs/imagenet_others/source.yaml MODEL.USE_CLIP True MODEL.ARCH ViT-B-16 MODEL.WEIGHTS openai CLIP.PROMPT_MODE ensemble

The runtime error found
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same

**Comment by IFTEE-KUET-CSE** [comment]
solved

**Comment by SydCS** [comment]
Solved.
MIXED_PRECISION True 
or
@autocast(True)
