### ISSUE TITLE
Can you provide the code of rmt method for semantic segmentation?

### ISSUE THREAD

**Issue by KingMV** [mariodoebler/test-time-adaptation#6]
Here is only the RMT code used for image classification tasks. Can you provide RMT code for semantic segmentation? thanks.

**Comment by mariodoebler** [comment]
Hi @KingMV,

we never investigated RMT for semantic segmentation, so unfortunately we can't provide any code. It shouldn't be too much effort to adapt the existing RMT code to the segmentation task.

Regards,
Mario
