### ISSUE TITLE
Cannot run the RMT method without exemplars

### ISSUE THREAD

**Issue by cygerts** [mariodoebler/test-time-adaptation#7]
Hi,
As in the RMT method I would like to run it in no source data mode. I set the cfg.Source.Percentage to 0.0 and it fails when creating the src loader in the constructor. 
Would you be able to provide the version that works without exemplars?

Best

**Comment by mariodoebler** [comment]
Hi @cygerts,

for running the source-free variant of RMT you have to pass `RMT.LAMBDA_CE_SRC 0.0` and not `SOURCE.PERCENTAGE 0.0`. E.g. `python test_time.py --cfg cfgs/imagenet_c/rmt.yaml RMT.LAMBDA_CE_SRC 0.0`. With `SOURCE.PERCENTAGE` you can control how much source data shall be used.

All the best,
Mario
